global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'system-metrics'
    static_configs:
      - targets: 
        - 'localhost:9100'  # Node Exporter
        - 'localhost:8080'  # Application metrics

  - job_name: 'spark-anomaly-detection'
    static_configs:
      - targets: ['localhost:4040']  # Spark UI metrics
    scrape_interval: 30s

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['localhost:9091']
    honor_labels: true

  - job_name: 'custom-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000']  # Custom application metrics

